config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :profiles
  resources :hash_tags
  resources :gazooies
  resources :comments
    devise_for :users
    #   resources :pages
    #    root 'startup/index#index'

    # resources :users
  
    resources :gazooies, only: [:index, :show, :create]
    resources :hash_tags, only: [:show]
    resources :comments, only: [:create]
    resources :news

    get '/:id' => 'pages#show'
    resources :pages, except: [:index]
    post 'comments'=>'comments#create'
    resources :profiles, :except => [:destroy, :new, :index, :create] do
        post "follow/:user_id", :to => "profiles#follow"
        delete "unfollow/:user_id", :to => "profiles#unfollow"
        get "followers/", :to => "profiles#followers"
        get "followees/", :to => "profiles#followees"
        get "mentions/", :to => "profiles#mentions"
    end
    get '/:id' => 'pages#show'
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
end

app/controllers/hash_tags_controller.rb
class HashTagsController < ApplicationController
  before_action :set_hash_tag, only: [:show, :edit, :update, :destroy]

  # GET /hash_tags
  # GET /hash_tags.json
  def index
    @hash_tags = HashTag.all
  end

  # GET /hash_tags/1
  # GET /hash_tags/1.json
  def show
  end

  # GET /hash_tags/new
  def new
    @hash_tag = HashTag.new
  end

  # GET /hash_tags/1/edit
  def edit
  end

  # POST /hash_tags
  # POST /hash_tags.json
  def create
    @hash_tag = HashTag.new(hash_tag_params)

    respond_to do |format|
      if @hash_tag.save
        format.html { redirect_to @hash_tag, notice: 'Hash tag was successfully created.' }
        format.json { render :show, status: :created, location: @hash_tag }
      else
        format.html { render :new }
        format.json { render json: @hash_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hash_tags/1
  # PATCH/PUT /hash_tags/1.json
  def update
    respond_to do |format|
      if @hash_tag.update(hash_tag_params)
        format.html { redirect_to @hash_tag, notice: 'Hash tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @hash_tag }
      else
        format.html { render :edit }
        format.json { render json: @hash_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hash_tags/1
  # DELETE /hash_tags/1.json
  def destroy
    @hash_tag.destroy
    respond_to do |format|
      format.html { redirect_to hash_tags_url, notice: 'Hash tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hash_tag
      @hash_tag = HashTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hash_tag_params
      params.require(:hash_tag).permit(:name)
    end
end

app/helpers/hash_tags_helper.rb
module HashTagsHelper
end

app/views/hash_tags/_form.html.erb
<%= form_with(model: hash_tag, local: true) do |form| %>
  <% if hash_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hash_tag.errors.count, "error") %> prohibited this hash_tag from being saved:</h2>

      <ul>
      <% hash_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hash_tags/edit.html.erb
<h1>Editing Hash Tag</h1>

<%= render 'form', hash_tag: @hash_tag %>

<%= link_to 'Show', @hash_tag %> |
<%= link_to 'Back', hash_tags_path %>

app/views/hash_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hash Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hash_tags.each do |hash_tag| %>
      <tr>
        <td><%= hash_tag.name %></td>
        <td><%= link_to 'Show', hash_tag %></td>
        <td><%= link_to 'Edit', edit_hash_tag_path(hash_tag) %></td>
        <td><%= link_to 'Destroy', hash_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hash Tag', new_hash_tag_path %>

app/views/hash_tags/new.html.erb
<h1>New Hash Tag</h1>

<%= render 'form', hash_tag: @hash_tag %>

<%= link_to 'Back', hash_tags_path %>

app/views/hash_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hash_tag.name %>
</p>

<%= link_to 'Edit', edit_hash_tag_path(@hash_tag) %> |
<%= link_to 'Back', hash_tags_path %>