config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :profiles
  resources :hash_tags
  resources :gazooies
  resources :comments
    devise_for :users
    #   resources :pages
    #    root 'startup/index#index'

    # resources :users
  
    resources :gazooies, only: [:index, :show, :create]
    resources :hash_tags, only: [:show]
    resources :comments, only: [:create]
    resources :news

    get '/:id' => 'pages#show'
    resources :pages, except: [:index]
    post 'comments'=>'comments#create'
    resources :profiles, :except => [:destroy, :new, :index, :create] do
        post "follow/:user_id", :to => "profiles#follow"
        delete "unfollow/:user_id", :to => "profiles#unfollow"
        get "followers/", :to => "profiles#followers"
        get "followees/", :to => "profiles#followees"
        get "mentions/", :to => "profiles#mentions"
    end
    get '/:id' => 'pages#show'
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:avatar, :background, :user_id, :name, :place, :website, :bio)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :background %>
    <%= form.text_field :background %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Background</th>
      <th>User</th>
      <th>Name</th>
      <th>Place</th>
      <th>Website</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.avatar %></td>
        <td><%= profile.background %></td>
        <td><%= profile.user_id %></td>
        <td><%= profile.name %></td>
        <td><%= profile.place %></td>
        <td><%= profile.website %></td>
        <td><%= profile.bio %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avatar:</strong>
  <%= @profile.avatar %>
</p>

<p>
  <strong>Background:</strong>
  <%= @profile.background %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @profile.place %>
</p>

<p>
  <strong>Website:</strong>
  <%= @profile.website %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>